server:
  port: ${PORT_EUREKA:8761}
spring:
  application:
      name:eureka
eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/